root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "" # don't run the binary directly
full_bin = "dlv exec ./tmp/main --headless --listen=:2345 --api-version=2 --accept-multiclient"

  # Faster & cleaner feedback
  delay = 500
  kill_delay = "300ms"
  send_interrupt = true
  stop_on_error = false

  # Watch settings
  include_ext = ["go","tpl","tmpl","html","env","json","yaml","yml"]
  exclude_dir = ["assets","tmp","vendor","testdata",".git"]
  exclude_regex = ["_test.go$"]

  # Show build errors in terminal (set to "" to print here)
  log = ""

  # If file changes aren't detected (e.g., Docker bind mount on macOS), flip this:
  poll = false
  poll_interval = 0

[log]
  time = true
  silent = false
  main_only = false

[color]
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[screen]
  clear_on_rebuild = false
  keep_scroll = true

[misc]
  clean_on_exit = false
